//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormInfoSinhVien.thanhnho {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSinhVien", Namespace= "http://tempuri.org/", ItemName="sinhVien")]
    [System.SerializableAttribute()]
    public class ArrayOfSinhVien : System.Collections.Generic.List<FormInfoSinhVien.thanhnho.sinhVien> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sinhVien", Namespace= "http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class sinhVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string khoaField;
        
        private int tuoiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string maSV {
            get {
                return this.maSVField;
            }
            set {
                if ((object.ReferenceEquals(this.maSVField, value) != true)) {
                    this.maSVField = value;
                    this.RaisePropertyChanged("maSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameField, value) != true)) {
                    this.fullNameField = value;
                    this.RaisePropertyChanged("fullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lop {
            get {
                return this.lopField;
            }
            set {
                if ((object.ReferenceEquals(this.lopField, value) != true)) {
                    this.lopField = value;
                    this.RaisePropertyChanged("lop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string khoa {
            get {
                return this.khoaField;
            }
            set {
                if ((object.ReferenceEquals(this.khoaField, value) != true)) {
                    this.khoaField = value;
                    this.RaisePropertyChanged("khoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int tuoi {
            get {
                return this.tuoiField;
            }
            set {
                if ((this.tuoiField.Equals(value) != true)) {
                    this.tuoiField = value;
                    this.RaisePropertyChanged("tuoi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace= "http://tempuri.org/", ConfigurationName="thanhnho.WebService1Soap")]
    public interface WebService1Soap {

        // CODEGEN: Generating message contract since element name maSv from namespace http://tempuri.org/is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action= "http://tempuri.org/add", ReplyAction="*")]
        FormInfoSinhVien.thanhnho.addResponse add(FormInfoSinhVien.thanhnho.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action= "http://tempuri.org/add", ReplyAction="*")]
        System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.addResponse> addAsync(FormInfoSinhVien.thanhnho.addRequest request);

        // CODEGEN: Generating message contract since element name listDSResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action= "http://tempuri.org/listDS", ReplyAction="*")]
        FormInfoSinhVien.thanhnho.listDSResponse listDS(FormInfoSinhVien.thanhnho.listDSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action= "http://tempuri.org/listDS", ReplyAction="*")]
        System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.listDSResponse> listDSAsync(FormInfoSinhVien.thanhnho.listDSRequest request);

        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action= "http://tempuri.org/ds_id", ReplyAction="*")]
        FormInfoSinhVien.thanhnho.ds_idResponse ds_id(FormInfoSinhVien.thanhnho.ds_idRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action= "http://tempuri.org/ds_id", ReplyAction="*")]
        System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.ds_idResponse> ds_idAsync(FormInfoSinhVien.thanhnho.ds_idRequest request);

        // CODEGEN: Generating message contract since element name ten from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action= "http://tempuri.org/ds_theoTen", ReplyAction="*")]
        FormInfoSinhVien.thanhnho.ds_theoTenResponse ds_theoTen(FormInfoSinhVien.thanhnho.ds_theoTenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action= "http://tempuri.org/ds_theoTen", ReplyAction="*")]
        System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.ds_theoTenResponse> ds_theoTenAsync(FormInfoSinhVien.thanhnho.ds_theoTenRequest request);

        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action= "http://tempuri.org/xoaThanhVien", ReplyAction="*")]
        FormInfoSinhVien.thanhnho.xoaThanhVienResponse xoaThanhVien(FormInfoSinhVien.thanhnho.xoaThanhVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action= "http://tempuri.org/xoaThanhVien", ReplyAction="*")]
        System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.xoaThanhVienResponse> xoaThanhVienAsync(FormInfoSinhVien.thanhnho.xoaThanhVienRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="add", Namespace= "http://tempuri.org/", Order=0)]
        public FormInfoSinhVien.thanhnho.addRequestBody Body;
        
        public addRequest() {
        }
        
        public addRequest(FormInfoSinhVien.thanhnho.addRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://tempuri.org/")]
    public partial class addRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string maSv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fullName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lop;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string khoa;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int tuoi;
        
        public addRequestBody() {
        }
        
        public addRequestBody(string maSv, string fullName, string lop, string khoa, int tuoi) {
            this.maSv = maSv;
            this.fullName = fullName;
            this.lop = lop;
            this.khoa = khoa;
            this.tuoi = tuoi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addResponse", Namespace= "http://tempuri.org/", Order=0)]
        public FormInfoSinhVien.thanhnho.addResponseBody Body;
        
        public addResponse() {
        }
        
        public addResponse(FormInfoSinhVien.thanhnho.addResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://tempuri.org/")]
    public partial class addResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addResult;
        
        public addResponseBody() {
        }
        
        public addResponseBody(string addResult) {
            this.addResult = addResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listDSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listDS", Namespace= "http://tempuri.org/", Order=0)]
        public FormInfoSinhVien.thanhnho.listDSRequestBody Body;
        
        public listDSRequest() {
        }
        
        public listDSRequest(FormInfoSinhVien.thanhnho.listDSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listDSRequestBody {
        
        public listDSRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listDSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listDSResponse", Namespace= "http://tempuri.org/", Order=0)]
        public FormInfoSinhVien.thanhnho.listDSResponseBody Body;
        
        public listDSResponse() {
        }
        
        public listDSResponse(FormInfoSinhVien.thanhnho.listDSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://tempuri.org/")]
    public partial class listDSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormInfoSinhVien.thanhnho.ArrayOfSinhVien listDSResult;
        
        public listDSResponseBody() {
        }
        
        public listDSResponseBody(FormInfoSinhVien.thanhnho.ArrayOfSinhVien listDSResult) {
            this.listDSResult = listDSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_idRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_id", Namespace= "http://tempuri.org/", Order=0)]
        public FormInfoSinhVien.thanhnho.ds_idRequestBody Body;
        
        public ds_idRequest() {
        }
        
        public ds_idRequest(FormInfoSinhVien.thanhnho.ds_idRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://tempuri.org/")]
    public partial class ds_idRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public ds_idRequestBody() {
        }
        
        public ds_idRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_idResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_idResponse", Namespace= "http://tempuri.org/", Order=0)]
        public FormInfoSinhVien.thanhnho.ds_idResponseBody Body;
        
        public ds_idResponse() {
        }
        
        public ds_idResponse(FormInfoSinhVien.thanhnho.ds_idResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://tempuri.org/")]
    public partial class ds_idResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormInfoSinhVien.thanhnho.sinhVien ds_idResult;
        
        public ds_idResponseBody() {
        }
        
        public ds_idResponseBody(FormInfoSinhVien.thanhnho.sinhVien ds_idResult) {
            this.ds_idResult = ds_idResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_theoTenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_theoTen", Namespace= "http://tempuri.org/", Order=0)]
        public FormInfoSinhVien.thanhnho.ds_theoTenRequestBody Body;
        
        public ds_theoTenRequest() {
        }
        
        public ds_theoTenRequest(FormInfoSinhVien.thanhnho.ds_theoTenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://tempuri.org/")]
    public partial class ds_theoTenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ten;
        
        public ds_theoTenRequestBody() {
        }
        
        public ds_theoTenRequestBody(string ten) {
            this.ten = ten;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_theoTenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_theoTenResponse", Namespace= "http://tempuri.org/", Order=0)]
        public FormInfoSinhVien.thanhnho.ds_theoTenResponseBody Body;
        
        public ds_theoTenResponse() {
        }
        
        public ds_theoTenResponse(FormInfoSinhVien.thanhnho.ds_theoTenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://tempuri.org/")]
    public partial class ds_theoTenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormInfoSinhVien.thanhnho.ArrayOfSinhVien ds_theoTenResult;
        
        public ds_theoTenResponseBody() {
        }
        
        public ds_theoTenResponseBody(FormInfoSinhVien.thanhnho.ArrayOfSinhVien ds_theoTenResult) {
            this.ds_theoTenResult = ds_theoTenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class xoaThanhVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="xoaThanhVien", Namespace= "http://tempuri.org/", Order=0)]
        public FormInfoSinhVien.thanhnho.xoaThanhVienRequestBody Body;
        
        public xoaThanhVienRequest() {
        }
        
        public xoaThanhVienRequest(FormInfoSinhVien.thanhnho.xoaThanhVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://tempuri.org/")]
    public partial class xoaThanhVienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public xoaThanhVienRequestBody() {
        }
        
        public xoaThanhVienRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class xoaThanhVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="xoaThanhVienResponse", Namespace= "http://tempuri.org/", Order=0)]
        public FormInfoSinhVien.thanhnho.xoaThanhVienResponseBody Body;
        
        public xoaThanhVienResponse() {
        }
        
        public xoaThanhVienResponse(FormInfoSinhVien.thanhnho.xoaThanhVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://tempuri.org/")]
    public partial class xoaThanhVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool xoaThanhVienResult;
        
        public xoaThanhVienResponseBody() {
        }
        
        public xoaThanhVienResponseBody(bool xoaThanhVienResult) {
            this.xoaThanhVienResult = xoaThanhVienResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : FormInfoSinhVien.thanhnho.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<FormInfoSinhVien.thanhnho.WebService1Soap>, FormInfoSinhVien.thanhnho.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormInfoSinhVien.thanhnho.addResponse FormInfoSinhVien.thanhnho.WebService1Soap.add(FormInfoSinhVien.thanhnho.addRequest request) {
            return base.Channel.add(request);
        }
        
        public string add(string maSv, string fullName, string lop, string khoa, int tuoi) {
            FormInfoSinhVien.thanhnho.addRequest inValue = new FormInfoSinhVien.thanhnho.addRequest();
            inValue.Body = new FormInfoSinhVien.thanhnho.addRequestBody();
            inValue.Body.maSv = maSv;
            inValue.Body.fullName = fullName;
            inValue.Body.lop = lop;
            inValue.Body.khoa = khoa;
            inValue.Body.tuoi = tuoi;
            FormInfoSinhVien.thanhnho.addResponse retVal = ((FormInfoSinhVien.thanhnho.WebService1Soap)(this)).add(inValue);
            return retVal.Body.addResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.addResponse> FormInfoSinhVien.thanhnho.WebService1Soap.addAsync(FormInfoSinhVien.thanhnho.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.addResponse> addAsync(string maSv, string fullName, string lop, string khoa, int tuoi) {
            FormInfoSinhVien.thanhnho.addRequest inValue = new FormInfoSinhVien.thanhnho.addRequest();
            inValue.Body = new FormInfoSinhVien.thanhnho.addRequestBody();
            inValue.Body.maSv = maSv;
            inValue.Body.fullName = fullName;
            inValue.Body.lop = lop;
            inValue.Body.khoa = khoa;
            inValue.Body.tuoi = tuoi;
            return ((FormInfoSinhVien.thanhnho.WebService1Soap)(this)).addAsync(inValue);
        }
        

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormInfoSinhVien.thanhnho.listDSResponse FormInfoSinhVien.thanhnho.WebService1Soap.listDS(FormInfoSinhVien.thanhnho.listDSRequest request) {
            return base.Channel.listDS(request);
        }
        
        public FormInfoSinhVien.thanhnho.ArrayOfSinhVien listDS() {
            FormInfoSinhVien.thanhnho.listDSRequest inValue = new FormInfoSinhVien.thanhnho.listDSRequest();
            inValue.Body = new FormInfoSinhVien.thanhnho.listDSRequestBody();
            FormInfoSinhVien.thanhnho.listDSResponse retVal = ((FormInfoSinhVien.thanhnho.WebService1Soap)(this)).listDS(inValue);
            return retVal.Body.listDSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.listDSResponse> FormInfoSinhVien.thanhnho.WebService1Soap.listDSAsync(FormInfoSinhVien.thanhnho.listDSRequest request) {
            return base.Channel.listDSAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.listDSResponse> listDSAsync() {
            FormInfoSinhVien.thanhnho.listDSRequest inValue = new FormInfoSinhVien.thanhnho.listDSRequest();
            inValue.Body = new FormInfoSinhVien.thanhnho.listDSRequestBody();
            return ((FormInfoSinhVien.thanhnho.WebService1Soap)(this)).listDSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormInfoSinhVien.thanhnho.ds_idResponse FormInfoSinhVien.thanhnho.WebService1Soap.ds_id(FormInfoSinhVien.thanhnho.ds_idRequest request) {
            return base.Channel.ds_id(request);
        }
        
        public FormInfoSinhVien.thanhnho.sinhVien ds_id(string id) {
            FormInfoSinhVien.thanhnho.ds_idRequest inValue = new FormInfoSinhVien.thanhnho.ds_idRequest();
            inValue.Body = new FormInfoSinhVien.thanhnho.ds_idRequestBody();
            inValue.Body.id = id;
            FormInfoSinhVien.thanhnho.ds_idResponse retVal = ((FormInfoSinhVien.thanhnho.WebService1Soap)(this)).ds_id(inValue);
            return retVal.Body.ds_idResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.ds_idResponse> FormInfoSinhVien.thanhnho.WebService1Soap.ds_idAsync(FormInfoSinhVien.thanhnho.ds_idRequest request) {
            return base.Channel.ds_idAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.ds_idResponse> ds_idAsync(string id) {
            FormInfoSinhVien.thanhnho.ds_idRequest inValue = new FormInfoSinhVien.thanhnho.ds_idRequest();
            inValue.Body = new FormInfoSinhVien.thanhnho.ds_idRequestBody();
            inValue.Body.id = id;
            return ((FormInfoSinhVien.thanhnho.WebService1Soap)(this)).ds_idAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormInfoSinhVien.thanhnho.ds_theoTenResponse FormInfoSinhVien.thanhnho.WebService1Soap.ds_theoTen(FormInfoSinhVien.thanhnho.ds_theoTenRequest request) {
            return base.Channel.ds_theoTen(request);
        }
        
        public FormInfoSinhVien.thanhnho.ArrayOfSinhVien ds_theoTen(string ten) {
            FormInfoSinhVien.thanhnho.ds_theoTenRequest inValue = new FormInfoSinhVien.thanhnho.ds_theoTenRequest();
            inValue.Body = new FormInfoSinhVien.thanhnho.ds_theoTenRequestBody();
            inValue.Body.ten = ten;
            FormInfoSinhVien.thanhnho.ds_theoTenResponse retVal = ((FormInfoSinhVien.thanhnho.WebService1Soap)(this)).ds_theoTen(inValue);
            return retVal.Body.ds_theoTenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.ds_theoTenResponse> FormInfoSinhVien.thanhnho.WebService1Soap.ds_theoTenAsync(FormInfoSinhVien.thanhnho.ds_theoTenRequest request) {
            return base.Channel.ds_theoTenAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.ds_theoTenResponse> ds_theoTenAsync(string ten) {
            FormInfoSinhVien.thanhnho.ds_theoTenRequest inValue = new FormInfoSinhVien.thanhnho.ds_theoTenRequest();
            inValue.Body = new FormInfoSinhVien.thanhnho.ds_theoTenRequestBody();
            inValue.Body.ten = ten;
            return ((FormInfoSinhVien.thanhnho.WebService1Soap)(this)).ds_theoTenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormInfoSinhVien.thanhnho.xoaThanhVienResponse FormInfoSinhVien.thanhnho.WebService1Soap.xoaThanhVien(FormInfoSinhVien.thanhnho.xoaThanhVienRequest request) {
            return base.Channel.xoaThanhVien(request);
        }
        
        public bool xoaThanhVien(string id) {
            FormInfoSinhVien.thanhnho.xoaThanhVienRequest inValue = new FormInfoSinhVien.thanhnho.xoaThanhVienRequest();
            inValue.Body = new FormInfoSinhVien.thanhnho.xoaThanhVienRequestBody();
            inValue.Body.id = id;
            FormInfoSinhVien.thanhnho.xoaThanhVienResponse retVal = ((FormInfoSinhVien.thanhnho.WebService1Soap)(this)).xoaThanhVien(inValue);
            return retVal.Body.xoaThanhVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.xoaThanhVienResponse> FormInfoSinhVien.thanhnho.WebService1Soap.xoaThanhVienAsync(FormInfoSinhVien.thanhnho.xoaThanhVienRequest request) {
            return base.Channel.xoaThanhVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormInfoSinhVien.thanhnho.xoaThanhVienResponse> xoaThanhVienAsync(string id) {
            FormInfoSinhVien.thanhnho.xoaThanhVienRequest inValue = new FormInfoSinhVien.thanhnho.xoaThanhVienRequest();
            inValue.Body = new FormInfoSinhVien.thanhnho.xoaThanhVienRequestBody();
            inValue.Body.id = id;
            return ((FormInfoSinhVien.thanhnho.WebService1Soap)(this)).xoaThanhVienAsync(inValue);
        }
    }
}
